version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - media:/app/media
    ports:
      - 5432:5432
  redis:
    image: redis:latest

  hotel:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}

      - HTTP_PORT=${HTTP_PORT}
    
      - SECRET_KEY=${SECRET_KEY}
    
      - SMTP_SENDER=${SMTP_SENDER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
       
      - REDIS_ADDR=${REDIS_ADDR}
      
      - AUTHORIZATION_HEADER_KEY=${AUTHORIZATION_HEADER_KEY}
      - AUTHORIZATION_PAYLOAD_KEY=${AUTHORIZATION_PAYLOAD_KEY}

    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
  media: